AWSTemplateFormatVersion: '2010-09-09'
Description: DCVV Demo Lambda Container Deployment (DEMO ONLY)
Resources:
  DCVVDemoFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: dcvv-demo-lambda
      PackageType: Image
      Code:
        ImageUri: <your_ecr_image_uri>
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          DEMO_MODE: 'true'
      Architectures:
        - x86_64
      Role: <your_lambda_execution_role_arn> 